#!/usr/bin/env python3
"""End-to-end tests for hierarchical swarm topology execution.

Covers:
- _execute_hierarchical_runner routes via _execute_topology_runner correctly
- Subtasks execute in wave order (root before child before grandchild)
- workspace_root is accessible on subtasks at execution time
- Multi-file swarm: two files generated where one imports from the other
"""
from __future__ import annotations

import os
import sys
import tempfile
from pathlib import Path
from types import SimpleNamespace

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

os.environ.setdefault("THRENODY_TEST_MODE", "1")

from shared.config import TGsConfig
from shared.db import Database
from shared.orchestrator import AgentResult, Orchestrator, Provider
from shared.planner import ExecutionPlan, Planner, Subtask


# ---------------------------------------------------------------------------
# Test doubles
# ---------------------------------------------------------------------------

class TrackingProvider(Provider):
    """Records (subtask_id, workspace_root) on every execute() call."""

    def __init__(self) -> None:
        self.execution_order: list[int] = []
        self.observed_workspace_roots: list[str | None] = []

    def resolve_model(self, tier: str) -> str:
        return f"dummy-{tier}"

    def execute(self, subtask: Subtask, model: str,
                timeout: int = 120) -> str | None:
        self.execution_order.append(subtask.id)
        self.observed_workspace_roots.append(
            getattr(subtask, "workspace_root", None)
        )
        return f"output-{subtask.id}"

    def available_tiers(self) -> list[str]:
        return ["low", "medium", "high"]

    def provider_info(self) -> dict:
        return {"primary": "tracking-provider"}


class FileWritingProvider(Provider):
    """Writes a small Python file for each subtask to verify real file I/O."""

    def __init__(self) -> None:
        self.execution_order: list[int] = []

    def resolve_model(self, tier: str) -> str:
        return f"dummy-{tier}"

    def execute(self, subtask: Subtask, model: str,
                timeout: int = 120) -> str | None:
        self.execution_order.append(subtask.id)
        target = getattr(subtask, "target_file", None)
        if target:
            Path(target).parent.mkdir(parents=True, exist_ok=True)
            Path(target).write_text(f"# generated by subtask {subtask.id}\n")
        return f"output-{subtask.id}"

    def available_tiers(self) -> list[str]:
        return ["low", "medium", "high"]


class DummyPlanner(Planner):
    def __init__(self) -> None:
        self._backend = SimpleNamespace(call=lambda *a, **kw: None)

    def plan(self, *args, **kwargs):  # pragma: no cover
        raise NotImplementedError


# ---------------------------------------------------------------------------
# Plan builder helpers
# ---------------------------------------------------------------------------

def _hierarchical_chain_plan(workspace_root: str | None = None) -> ExecutionPlan:
    """Three-node chain: 1 → 2 → 3 (root, child, grandchild)."""
    subtasks = [
        Subtask(id=1, description="root task", tier="low", model="low",
                depends_on=[], workspace_root=workspace_root),
        Subtask(id=2, description="child task", tier="low", model="low",
                depends_on=[1], workspace_root=workspace_root),
        Subtask(id=3, description="grandchild task", tier="low", model="low",
                depends_on=[2], workspace_root=workspace_root),
    ]
    plan = ExecutionPlan(
        analysis="hierarchical-chain",
        subtasks=subtasks,
        waves=[[1], [2], [3]],
        total_agents=3,
        strategy="sequential",
        topology="hierarchical",
    )
    plan._topology_explicit = True
    return plan


def _make_orchestrator(provider: Provider,
                       db: Database | None = None) -> Orchestrator:
    return Orchestrator(TGsConfig(), provider, DummyPlanner(), db=db)


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

def test_hierarchical_topology_executes_root_before_children() -> None:
    provider = TrackingProvider()
    orchestrator = _make_orchestrator(provider)
    plan = _hierarchical_chain_plan()

    results = orchestrator.execute_plan(plan, execution_id="hier-e2e-order")

    assert provider.execution_order == [1, 2, 3], (
        f"expected [1,2,3] but got {provider.execution_order}"
    )
    assert set(results.keys()) == {1, 2, 3}
    for r in results.values():
        assert r.success


def test_hierarchical_subtasks_carry_workspace_root_at_execution_time() -> None:
    workspace = "/fake/project-root"
    provider = TrackingProvider()
    orchestrator = _make_orchestrator(provider)
    plan = _hierarchical_chain_plan(workspace_root=workspace)

    orchestrator.execute_plan(plan, execution_id="hier-e2e-ws")

    for observed in provider.observed_workspace_roots:
        assert observed == workspace, (
            f"subtask had workspace_root={observed!r}, expected {workspace!r}"
        )


def test_hierarchical_real_file_output_lands_in_workspace() -> None:
    with tempfile.TemporaryDirectory() as ws:
        provider = FileWritingProvider()
        orchestrator = _make_orchestrator(provider)

        subtasks = [
            Subtask(id=1, description="write module_b.py", tier="low",
                    model="low", depends_on=[],
                    target_file=str(Path(ws) / "module_b.py"),
                    workspace_root=ws),
            Subtask(id=2, description="write module_a.py (imports module_b)",
                    tier="low", model="low", depends_on=[1],
                    target_file=str(Path(ws) / "module_a.py"),
                    workspace_root=ws),
        ]
        plan = ExecutionPlan(
            analysis="multi-file-import-test",
            subtasks=subtasks,
            waves=[[1], [2]],
            total_agents=2,
            strategy="sequential",
            topology="hierarchical",
        )
        plan._topology_explicit = True

        orchestrator.execute_plan(plan, execution_id="hier-e2e-files")

        assert (Path(ws) / "module_b.py").exists(), "module_b.py not written"
        assert (Path(ws) / "module_a.py").exists(), "module_a.py not written"
        assert provider.execution_order == [1, 2], (
            "module_b (id=1) must be written before module_a (id=2)"
        )
